name: toolsight
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. 
# To see which dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  go_router: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_icons:
    android: "launcher_icon"
    image_path: "assets/logo.png"
